<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DotnetVersion)</TargetFramework>
    <OutputType>Library</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Xilium.CefGlue.Headless</RootNamespace>
    <AssemblyName>Xilium.CefGlue.Headless</AssemblyName>
    <Nullable>disable</Nullable>
    <PackageId>CefGlue.Headless$(PackageSuffix)</PackageId>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    <Authors>Marman-HP</Authors>
    <Copyright>Copyright © 2026 Marman-HP. Portions Copyright © XiliumHQ 2021, OutSystems 2021.</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\CefGlue.Common\BaseCefBrowser.cs">
      <Link>Common\BaseCefBrowser.cs</Link>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CefGlue.Common\CefGlue.Common.csproj">
      <PrivateAssets>none</PrivateAssets>
    </ProjectReference>
    <ProjectReference Include="..\CefGlue\CefGlue.csproj">
      <PrivateAssets>all</PrivateAssets>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.Direct3D11" />

    <PackageReference Include="System.Drawing.Common" />

  </ItemGroup>

</Project>
