<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DotnetVersion)</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Xilium.CefGlue.Headless.Server</RootNamespace>
    <AssemblyName>Xilium.CefGlue.Headless.Server</AssemblyName>
    <Nullable>disable</Nullable>
    <PackageId>CefGlue.Headless.Server$(PackageSuffix)</PackageId>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    <Authors>Marman-HP</Authors>
    <Copyright>Copyright © 2026 Marman-HP. Portions Copyright © XiliumHQ 2021, OutSystems 2021.</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CefGlue.Headless\CefGlue.Headless.csproj">
      <PrivateAssets>none</PrivateAssets>
    </ProjectReference>
  </ItemGroup>

</Project>
